# Generated by Django 3.2.8 on 2021-11-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_like_postview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='indir.png', upload_to='post'),
        ),
    ]
