# Generated by Django 3.2.8 on 2021-11-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_click'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='https://picsum.photos/200/300', upload_to='post'),
        ),
    ]
